name: CI

on:
  push:
    branches: [ main ]      
  pull_request:
    branches: [ main ]      

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Create zip artifact
        run: ./gradlew clean distZip

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app/build/distributions/app.zip

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: ./gradlew test